conversation/urls.py
from django.urls import path

from . import views
from .views import delete_conversation

app_name = 'conversation'


urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('conversation/<int:pk>/delete/', delete_conversation, name='delete_conversation'),
]

watchapp/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path


from . import views
from .forms import LoginForm

app_name = 'watchapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

watches/urls.py
from django.urls import path

from . import views 

app_name = 'watches'

urlpatterns = [
    path('', views.filtered_items, name='items'), 
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/submit_offer/', views.submit_offer, name='submit_offer'),
    path('watches/category/<str:category_name>/', views.filtered_items, name='watches_by_category'),  
    path('watches/filter/price/', views.filtered_items, name='filtered_watches_by_price'), 
    path('filtered_watches_by_year/', views.filtered_items, name='filtered_watches_by_year'),
    path('search/', views.search_items, name='search_items'),
] 

watchsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('watchapp.urls')),
    path('watches/', include('watches.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

watchapp/models.py
from django.db import models

# Create your models here.

watchapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User



class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl font-semibold text-center info'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email',
        'class': 'w-full py-4 px-6 rounded-xl font-semibold text-center info'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl font-semibold text-center info'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password again',
        'class': 'w-full py-4 px-6 rounded-xl font-semibold text-center info'
    }))

watchapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView

from watches.models import Category, Item

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')



class CustomLoginView(LoginView):
    template_name = 'core/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def render_to_response(self, context, **response_kwargs):
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            **response_kwargs
        )


def signup(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html',{
        'form': form,
        'categories': categories
    })

watchapp/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@100&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/4b8e303bca.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <title>{% block title %} {% endblock %} | Base </title>
</head>

<body class="bg-white">

    <nav
        class="py-6 flex flex-col sm:flex-row justify-center items-center border-b border-gray-200 px-4 lg:px-6 py-2.5 bg-gray-700 nav-bar">
        <a href="/" class="flex items-center main-header-cursive text-white text-5xl justify-center lg:justify-start">
            Watches By Karl
        </a>
        </div>
        <div class="mt-4 ml-5 sm:mt-0 space-x-4 flex flex-wrap items-center justify-center">
            {% if request.user.is_authenticated %}
            <span class="text-lg rounded-lg main-header-cursive text-white">Hello there
                {{ request.user.username }}</span>
            <a href="{% url 'watches:items' %}"
                class="px-2 py-2 text-white main-header-cursive hover:text-teal-700">BROWSE</a>
            <a href="{% url 'conversation:inbox' %}"
                class="px-2 py-2 text-white main-header-cursive hover:text-teal-700">INBOX</a>
            <div class="relative text-center">
                <div class="inline-block">
                    <button class="py-2 px-2 text-white main-header-cursive focus:outline-none hover:text-teal-700">
                        BRANDS IN STOCK
                    </button>
                    <div class="dropdown-container">
                        <ul>
                            <li><a href="{% url 'watches:items' %}?query={{ query }}">All</a>
                            {% for category in categories %}
                            <li>
                                <a href="{% url 'watches:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <a href="{% url 'watchapp:logout' %}"
                class="px-2 py-2 text-lg text-white main-header-cursive hover:text-red-500">LOG
                OUT</a>
            {% else %}
            <a href="{% url 'watches:items' %}"
                class="px-2 py-2 text-white main-header-cursive hover:text-teal-700">BROWSE</a>
            <div class="relative text-center">
                <div class="inline-block">
                    <button class="py-2 px-2 text-white main-header-cursive focus:outline-none hover:text-teal-700">
                        BRANDS IN STOCK
                    </button>
                    <div class="dropdown-container">
                        <ul>
                            <li><a href="{% url 'watches:items' %}">All</a></li>
                            {% for category in categories %}
                            <li>
                                <a href="{% url 'watches:items' %}?category={{ category.id }}">{{ category.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <a href="{% url 'watchapp:signup' %}"
                class="px-4 py-2 text-lg rounded-lg bg-sky-600 text-white rounded-xl hover:bg-teal-700 main-header-cursive">Sign
                up</a>
            <a href="{% url 'watchapp:login' %}"
                class="px-4 py-2 text-lg bg-indigo-700 text-white rounded-xl hover:bg-teal-700 main-header-cursive">Sign
                in</a>
            {% endif %}
        </div>
    </nav>


    <div class="px-4 sm:px-6 py-6">
        {% block content %}

        {% endblock %}

    </div>

    <footer
        class="py-6 px-4 sm:px-6 flex flex-wrap justify-between bg-gray-700 bottom-0 border-gray-200 inset-x-0 mt-20 pt-20">
        <div class="w-full sm:w-2/3 pr-0 sm:pr-10">
            <h3 class="mb-5 font-semibold main-header-cursive text-white text-center">About</h3>
            <span class="text-lg text-bold bitter-font-bold text-white">
                Our curated collection includes renowned brands such as Breitling, PANERAI, Cartier, Tudor, Tag Heuer,
                Rolex and many more.
                Having been in watch business for over 5 years you can rest assured that every timepiece sold by us has
                been carefully inspected against theft & Authenticity
                <br>
                We can be contacted at any time through eBay messages if you have any
                questions, comments, or product requests. We will respond to you within 24 hours and do our best to help
                you out! We encourage our customers to contact us with any questions or concerns! We'd like to be sure
                you are completely satisfied with your purchase.
            </span>
        </div>
        <div class="w-full sm:w-1/3 mt-4 sm:mt-0">
            <h3 class="mb-5 font-semibold main-header-cursive text-center text-white">Additional Info</h3>
            <ul class="space-y-2">
                <li><a href="#"
                        class="text-lg text-teal-500 hover:text-teal-700 main-header-cursive mr-4">Payment</a><span
                        class="text-right text-sm text-white">To be made within 2 hours of purchase. Otherwise, the sale
                        will be canceled.</span></li>
                <li><a href="#"
                        class="text-lg text-teal-500 hover:text-teal-700 main-header-cursive mr-4">Contact</a><span
                        class="text-right text-sm text-white">Feel free to get in touch with us using our convenient
                        messaging system on the website. Alternatively, you can reach out to us via email at
                        watchesbykarl@gmail.com. We're here to assist you with any inquiries or requests you may have!"

                        This message encourages buyers to use the website's messaging system while also providing your
                        email address as an alternative contact method.</span></li>
                <li><a href="#"
                        class="text-lg text-teal-500 hover:text-teal-700 main-header-cursive mr-4">Shipping</a><span
                        class="text-right text-sm text-white">Purchases over eBay are shipped strictly to the UK. If
                        international, please contact me, and I will arrange a quote. Payment must be made before the
                        product is shipped.</span></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700 main-header-cursive mr-4">Terms and
                        conditions &
                        Disclaimer</a><span class="text-sm text-white">I reserve the right to withdraw from the sale if
                        the purchaser holds less
                        than 10 positive eBay reviews.
                        I appreciate and welcome offers. However, there is an auto-reject option set in place for a
                        reason. Please keep in mind watches are also advertised on Facebook Marketplace /
                        Chrono24</span>
                </li>
            </ul>
        </div>
    </footer>

    <script>
        var currentURL = window.location.href;


        if (currentURL.indexOf("/watches/") !== -1) {

            document.querySelector('.nav-bar').classList.add('browse-page-nav');
        } else {

            document.querySelector('.nav-bar').classList.remove('browse-page-nav');
        }
        $(document).ready(function () {
            $("#imageCarousel").owlCarousel({
                items: 1,
                loop: true,
                nav: true,
                dots: false,
                navText: ["<i class='fa-solid fa-chevron-left text-left'></i>",
                    "<i class='fa-solid fa-chevron-right'></i>"
                ]
            });
        });

        function validateNumber(input) {

            input.value = input.value.replace(/[^0-9]/g, '');
        }
    </script>

</body>

</html>

watchapp/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
    <h1> The contact page </h1>


    <!-- DO NOT NEED TO USE THIS , NOW OBSOLETE!, TO LEAVE URLS AND VIEWS IF I END UP USING IT LATER ON -->
{% endblock %}

watchapp/templates/core/index.html
{% extends 'core/base.html' %}
{% load humanize %}
{% load static %}

{% block title %} Welcome {% endblock %}

{% block content %}
<span class="block text-center p-10 m-10 text-2xl bitter-font-bold">
    <i class="fas fa-handshake mr-5 ml-5"></i> Buy <i class="fas fa-dollar-sign mr-5 ml-5"></i> Sell <i class="fas fa-exchange-alt mr-5 ml-5"></i> Trade pre-owned watches
</span>
<img src="https://watches4u.pl/modules/themeconfigurator/img/68088bb83167b1de2bfa6e98df36c9814f6a08b0_men.jpg" class="w-full h-1/4" alt="Wide and Short Image">
<div class="mt-6 px-6 py-12 rounded-xl bg-gray-100">
    <h2 class="mb-12 text-center w-full cursive-padding-size"> Available watches </h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-6">
        {% for watch in items %}
        <div class="mb-6">
            <a href="{% url 'watches:detail' watch.id %}">
                <div>
                    {% if watch.main_image %}
                    <img src="{{ watch.main_image.url }}" class="w-full h-auto rounded-lg shadow-md"
                        alt="{{ watch.name }}">
                    {% else %}
                    <img src="{% static 'path/to/placeholder/image.png' %}" class="w-full h-auto rounded-lg shadow-md"
                        alt="{{ watch.name }}">
                    {% endif %}

                    <div class="p-6 rounded-xl mt-4">
                        <h2 class="text-lg uppercase text-center span">
                            {{ watch.name }}
                        </h2>
                        <p class="text-center font-semibold bitter-font-bold mt-4"> Price : {{ watch.price|intcomma }} <i
                                class="fa-solid fa-sterling-sign"></i></p>
                        <p class="text-center mt-1 font-semibold bitter-font-bold"> Year : <span
                                class="text-center bitter-font-bold">{{ watch.year }} </span></p>
                        <div class="flex justify-center mt-2">
                            <div class="text-center mr-4">
                                <span class="font-semibold text-s bitter-font-bold">With box</span>
                                {% if watch.has_box %}
                                <span class="font-light text-s"><i class="fa-regular fa-circle-check"></i></span>
                                {% else %}
                                <span class="font-light text-s"><i class="fa-regular fa-circle-xmark"></i></span>
                                {% endif %}
                            </div>

                            <!-- Check if has_papers is True and display the icon accordingly -->
                            <div class="text-center">
                                <span class="font-semibold text-s bitter-font-bold">With papers</span>
                                {% if watch.has_papers %}
                                <span class="font-light text-s"><i class="fa-regular fa-circle-check"></i></span>
                                {% else %}
                                <span class="font-light text-s"><i class="fa-regular fa-circle-xmark"></i></span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="flex flex-col items-center mt-2">
                            <p class="text-center text-xs">
                                <a href="{{ watch.ebay_link }}" target="_blank">
                                    <i class="fa-brands fa-ebay text-4xl"></i>
                                </a>
                            </p>
                            <a href="{% url 'watches:submit_offer' watch.pk %}"
                                class="mt-2 px-4 py-1 font-semibold bg-gray-600 text-white hover:bg-teal-700 rounded-xl main-header-cursive">Submit
                                an Offer</a>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>


<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-center cursive-padding-size"> Discover Fine Timepieces from the below Brands : </h2>

    <div class="grid grid-cols-1 text-center">
        {% for category in categories %}
        <div>
            <a href="{% url 'watches:watches_by_category' category_name=category.name %}">
                <div class="p-6 bg-white-rounded-b-xl">
                    <h2 class="text-2xl font-semibold uppercase tracking-widest">{{ category.name }}</h2>
                    <p class="text-gray-500 main-header-cursive mt-6">{{ category.items.count }} Items</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

watchapp/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<section class="bg-gray-700">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <a href="#" class="flex items-center mb-6 login-cursive text-5xl text-white">
          Watches By Karl
      </a>
      <div class="w-full rounded-lg shadow border md:mt-0 sm:max-w-md xl:p-0 bg-gray-900 border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 class="bitter-grey-medium text-center text-xl font-bold leading-tight tracking-tight text-white md:text-2xl">
                  Sign in to your account
              </h1>
              <form method="post" action=".">
                  {% csrf_token %}
                  <div>
                      <label for="username" class="bitter-grey-medium text-center block mb-2 text-sm font-semibold text-white">Username</label>
                      <input type="text" name="username" id="username" class="w-full py-4 px-6 rounded-xl font-semibold text-center info" required="">
                  </div>
                  <div>
                      <label for="password" class="bitter-grey-medium text-center block mb-2 text-sm font-semibold text-white">Password</label>
                      <input type="password" name="password" id="password" class="w-full py-4 px-6 rounded-xl font-semibold text-center info" required="">
                  </div>
                  <div class="flex items-center justify-between">
                      <div class="flex items-start">
                          <div class="flex items-center h-5">
                            <input id="remember" type="checkbox" class="mt-4 w-4 h-4 border border-gray-300 rounded bg-gray-700 focus:ring-3 focus:ring-primary-300 ring-offset-gray-800">
                          </div>
                          <div class="ml-3 text-sm mt-2">
                            <label for="remember" class="text-white">Remember me</label>
                          </div>
                      </div>
                      <a href="#" class="mt-2 text-sm font-medium text-primary-600 hover:underline text-white">Forgot password?</a>
                  </div>
                  <button type="submit" class="w-full bitter-grey-medium font-semibold text-sm text-white hover:underline">- Sign in... -</button>
                  <p class="text-sm text-center mt-1 text-white bitter-grey-medium">
                    Don't have an account yet? 
                  </p>
                  <p class="text-sm text-center mt-1">
                    <a href="{% url 'watchapp:signup' %}" class="font-semibold hover:underline text-sm text-white bitter-grey-medium">- Sign up -</a>
                  </p>
              </form>
          </div>
      </div>
  </div>
</section>
{% endblock %}

watchapp/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign up {% endblock %}

{% block content %}
<section class="bg-gray-700">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <a href="#" class="flex items-center mb-6 login-cursive text-5xl text-white">
        Watches By Karl
      </a>
      <div class="w-full rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0 bg-gray-900 border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 class="bitter-grey-medium text-center text-xl font-bold leading-tight tracking-tight text-white md:text-2xl">
                  Sign up for an account
              </h1>
              <form method="post" action=".">
                  {% csrf_token %}
                  <div>
                      <label for="username" class="bitter-grey-medium text-center block mb-2 text-sm font-semibold text-white">Username</label>
                      {{ form.username }}
                  </div>
                  <div>
                      <label for="email" class="bitter-grey-medium text-center block mb-2 text-sm font-semibold text-white">Email</label>
                      {{ form.email }}
                  </div>
                  <div>
                      <label for="password1" class="bitter-grey-medium text-center block mb-2 text-sm font-semibold text-white">Password</label>
                      {{ form.password1 }}
                  </div>
                  <div>
                      <label for="password2" class="bitter-grey-medium text-center block mb-2 text-sm font-semibold text-white">Repeat Password</label>
                      {{ form.password2 }}
                  </div>
                  {% if form.errors or form.non_field_errors %}
                      <div class="mb-3 p-6 bg-red-100 rounded-xl">
                          {% for field in form %}
                              {{ field.errors }}
                          {% endfor %}
                          {{ form.non_field_errors }}
                      </div>
                  {% endif %}
                  <button type="submit" class="w-full text-sm text-white bitter-grey-medium">- Sign up... -</button>
                  <p class="text-sm text-white text-center mt-1 bitter-grey-medium">
                    Already have an account? 
                </p>
                <p class="text-sm text-center mt-1">
                    <a href="{% url 'watchapp:login' %}" class="bitter-grey-medium font-semibold text-sm text-white hover:underline">- Sign in -</a>
                </p>
              </form>
          </div>
      </div>
  </div>
</section>
{% endblock %}