conversation/urls.py
from django.urls import path

from . import views
from .views import delete_conversation

app_name = 'conversation'


urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('conversation/<int:pk>/delete/', delete_conversation, name='delete_conversation'),
]

watches/urls.py
from django.urls import path

from . import views 

app_name = 'watches'

urlpatterns = [
    path('', views.filtered_items, name='items'), 
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/submit_offer/', views.submit_offer, name='submit_offer'),
    path('watches/category/<str:category_name>/', views.filtered_items, name='watches_by_category'),  
    path('watches/filter/price/', views.filtered_items, name='filtered_watches_by_price'), 
    path('filtered_watches_by_year/', views.filtered_items, name='filtered_watches_by_year'),
    path('search/', views.search_items, name='search_items'),
] 

watchsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('watchapp.urls')),
    path('watches/', include('watches.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

watches/models.py
from django.contrib.auth.models import User
from django.db import models
from cloudinary.models import CloudinaryField

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    main_image = CloudinaryField('main_image', default='https://as2.ftcdn.net/v2/jpg/00/89/55/15/1000_F_89551596_LdHAZRwz3i4EM4J0NHNHy2hEUYDfXc0j.jpg')
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    ebay_link = models.URLField(blank=True, null=True)
    item_offers = models.ManyToManyField('Offer', related_name='items', blank=True)
    year = models.PositiveIntegerField(null=True, blank=True)
    has_box = models.BooleanField(default=False)
    has_papers = models.BooleanField(default=False)
    water_resistance = models.CharField(max_length=100, blank=True, null=True)
    case_size = models.CharField(max_length=20, blank=True, null=True)
    case_material = models.CharField(max_length=50, blank=True, null=True)
    movement = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name

class Offer(models.Model):
    item = models.ForeignKey(Item, related_name='offers', on_delete=models.CASCADE)
    offer_amount = models.DecimalField(max_digits=10, decimal_places=2)  # Use DecimalField for currency
    is_accepted = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='offers', on_delete=models.CASCADE)

    def __str__(self):
        return f'Offer of ${self.offer_amount} on {self.item.name}'



class ItemImage(models.Model):
    item = models.ForeignKey(Item, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='item_images/')
    # You can add more fields if needed, e.g., image description, position, etc.

    def __str__(self):
        return self.item.name + ' Image'

watches/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required

from .models import Category, Item, Offer
from conversation.models import Conversation, ConversationMessage


def filtered_items(request, category_name=None):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    min_year = request.GET.get('min_year')
    max_year = request.GET.get('max_year')

    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_name:
        # Filter by category name if provided
        items = items.filter(category__name=category_name)

    if category_id:
        # Filter by category_id if provided
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    # Apply price filter if both min_price and max_price are provided
    if min_price and max_price:
        items = items.filter(price__range=(min_price, max_price))
    elif min_price:
        items = items.filter(price__gte=min_price)
    elif max_price:
        items = items.filter(price__lte=max_price)

    # Apply year filter if both min_year and max_year are provided
    if min_year and max_year:
        items = items.filter(year__range=(min_year, max_year))
    elif min_year:
        items = items.filter(year__gte=min_year)
    elif max_year:
        items = items.filter(year__lte=max_year)

    return render(request, 'watches/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
        'min_price': min_price,
        'max_price': max_price,
        'min_year': min_year,
        'max_year': max_year,
        'category_name': category_name, 
    })



def search_items(request):
    query = request.GET.get('query', '')

    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)  

    if query:
        items = items.filter(
            Q(name__icontains=query) |  # item name
            Q(description__icontains=query)  # item description
        )

    

    # Redirect back to the main items view after searching
    return render(request, 'watches/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'min_price': None,  
        'max_price': None,
        'min_year': None,
        'max_year': None,
    })



def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    categories = Category.objects.all()

    return render(request, 'watches/detail.html', {
        'item': item,
        'related_items': related_items,
        'categories': categories,
    })

@login_required
def submit_offer(request, pk):
    item = get_object_or_404(Item, pk=pk)
    categories = Category.objects.all()

    if request.method == 'POST':
        offer_amount = request.POST.get('offer_amount')

        # Create a new conversation for the offer
        conversation = Conversation.objects.create(item=item)
        conversation.members.add(request.user)
        conversation.members.add(item.created_by)

        # Create the offer message within the conversation
        offer_message = ConversationMessage.objects.create(
            conversation=conversation,
            content = f"I would like to offer : £{offer_amount}.",
            created_by=request.user,
            is_offer=True  # Set this as an offer message
        )

        return render(request, 'watches/thanks.html', {'item': item, 'categories': categories})

    return render(request, 'watches/submit_offer.html', {'item': item, 'categories': categories})

watches/templates/watches/detail.html
{% extends 'core/base.html' %}
{% load humanize %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="container mx-auto p-4">
    <!-- Watch title -->
    <h1 class="text-5xl font-semibold text-center p-10 bitter-font-bold">{{ item.name }}</h1>

    <div class="flex flex-col-reverse md:flex-row items-center">
        <!-- Owl Carousel for additional images -->
        <div class="w-full md:w-1/2">
            <div class="mt-4 owl-carousel owl-theme" id="imageCarousel">
                {% for image in item.images.all %}
                <div class="item">
                    <img src="{{ image.image.url }}" alt="{{ item.name }}"
                        class="w-full h-auto max-w-lg max-h-126 rounded-lg cursor-pointer">
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Description on the right -->
        <div class="w-full md:w-1/2 pl-4 p-6 bg-gray-200 rounded">
            <div class="flex flex-col">
                <!-- Right side with description, contact, price, and buttons -->
                {% if item.description %}
                <div class="text-gray-800 mb-6">
                    <i class="fa-regular fa-copy mb-4 mr-2 text-2xl"></i>
                    <strong class="roboto-font text-2xl">Description:</strong><br>
                    <span class="login-cursive font-semibold">{{ item.description }}</span>
                </div>
                {% endif %}
                <p class="text-gray-800 mb-6">
                    <i class="fa-solid fa-address-book mb-4 mr-2 text-2xl"></i> <strong class="roboto-font text-2xl">Contact
                        :</strong><br>
                    <span class="login-cursive text-2xl font-semibold inline-block">{{ item.created_by.username }} @
                        Orlandinikarlo@gmail.com</span>
                    <a href="{{ item.ebay_link }}" target="_blank">
                        <i class="fa-brands fa-ebay text-4xl inline-block text-blue-400"></i>
                    </a>
                </p>
                <p class="text-gray-800 mb-6">
                    <i class="fa-solid fa-tags text-2xl mb-4 mr-2"></i> <strong class="roboto-font text-2xl">Price :</strong><br>
                    <span class="m-4 login-cursive text-2xl font-semibold">{{ item.price|intcomma }} £</span>
                </p>
                <div class="flex flex-col md:flex-row">
                    <a href="{% url 'watches:submit_offer' item.pk %}"
                       class="mt-4 md:mt-0 md:mr-4 px-4 py-2 text-lg font-semibold bg-red-800 text-white hover:bg-red-900 rounded roboto-font">Submit an offer</a>
                    <a href="{% url 'conversation:new' item.id %}"
                       class="mt-4 md:mt-0 px-4 py-2 text-lg font-semibold bg-black text-white hover:bg-black rounded roboto-font">Message seller</a>
                </div>
            </div>
        </div>
    </div>

    <div class="p-8 rounded-xl mt-8 bg-gray-200">
        <h2 class="mb-8 font-semibold bitter-font-bold text-3xl text-center p-8"><i class="fa-solid fa-gears mr-4"></i>
            Specifications</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 roboto-font font-bold">
            <div class="mb-4">
                <i class="fa-solid fa-box mr-5"></i><strong class="bitter-font-bold font-bold">Box: </strong>
                {% if item.has_box %} Yes {% else %} No {% endif %}
            </div>
            <div class="mb-4">
                <i class="fa-regular fa-paste mr-5"></i><strong class="bitter-font-bold font-bold">Papers:</strong>
                {% if item.has_papers %} Yes {% else %} No {% endif %}
            </div>
            <div class="mb-4">
                <i class="fa-solid fa-calendar-days mr-5"></i><strong class="bitter-font-bold font-bold">Year:</strong>
                {{ item.year }}
            </div>
            <div class="mb-4">
                <i class="fa-solid fa-water-ladder mr-5"></i> <strong class="bitter-font-bold font-bold">Water Resistance:</strong> {{ item.water_resistance }}
            </div>
            <div class="mb-4">
                <i class="fa-solid fa-ruler mr-5"></i><strong class="bitter-font-bold font-bold">Case Size:</strong>
                {{ item.case_size }}
            </div>
            <div class="mb-4">
                <i class="fa-solid fa-recycle mr-5"></i> <strong class="bitter-font-bold font-bold">Case Material:</strong>
                {{ item.case_material }}
            </div>
            <div class="mb-4">
                <i class="fa-regular fa-clock mr-5"></i> <strong class="bitter-font-bold font-bold">Movement:</strong>
                {{ item.movement }}
            </div>
        </div>
    </div>
</div>

<div class="mt-10 px-4 py-12 bg-gray-100">
    <h2 class="mb-8 text-4xl text-center uppercase w-full roboto-font font-bold">Related Items</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {% for watch in related_items %}
        <div>
            <a href="{% url 'watches:detail' watch.id %}">
                <div>
                    <img src="{{ watch.main_image.url }}" class="w-2/4 h-auto object-contain mx-auto rounded">
                    <div class="p-6 rounded-xl mt-4">
                        <h2 class="text-lg uppercase text-center span">
                            {{ watch.name }}
                        </h2>
                        <p class="text-center font-semibold bitter-font-bold mt-4"> Price : {{ watch.price|intcomma }} <i
                                class="fa-solid fa-sterling-sign"></i></p>
                        <p class="text-center mt-1 font-semibold bitter-font-bold"> Year : <span
                                class="text-center bitter-font-bold">{{ watch.year }} </span></p>
                        <div class="flex justify-center mt-2">
                            <div class="text-center mr-4">
                                <span class="font-semibold text-s bitter-font-bold">With box</span>
                                {% if watch.has_box %}
                                <span class="font-light text-s"><i class="fa-solid fa-circle-check"></i></span>
                                {% else %}
                                <span class="font-light text-s"><i class="fa-regular fa-circle-xmark"></i></span>
                                {% endif %}
                            </div>

                            <!-- Check if has_papers is True and display the icon accordingly -->
                            <div class="text-center">
                                <span class="font-semibold text-s bitter-font-bold">With papers</span>
                                {% if watch.has_papers %}
                                <span class="font-light text-s"><i class="fa-solid fa-circle-check"></i></span>
                                {% else %}
                                <span class="font-light text-s"><i class="fa-regular fa-circle-xmark"></i></span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="flex flex-col items-center mt-2">
                            <p class="text-center text-xs">
                                <a href="{{ watch.ebay_link }}" target="_blank">
                                    <i class="fa-brands fa-ebay text-4xl"></i>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

watches/templates/watches/items.html
{% extends 'core/base.html' %}
{% load humanize %}

{% block title %}
{% if category_id %}
Watches by
{% for category in categories %}
{% if category.id == category_id %}
{{ category.name }}
{% endif %}
{% endfor %}
{% else %}
Watches by Filter
{% endif %}
{% endblock %}

{% block content %}
<!-- Filter compartment below the main image -->
<div class="w-full bg-gray-200 p-4 rounded-xl mt-4">
    <div class="mb-4">
        <div class="text-center">
            <div class="relative text-center">
                <div class="inline-block">
                    <button
                        class="py-2 px-2 rounded-md brands-cursive-padding-color btn-categories focus:outline-none hover:bg-gray-200">
                        AVAILABLE BRANDS
                    </button>
                    <div class="dropdown-container">
                        <ul>
                            <li><a href="{% url 'watches:items' %}?query={{ query }}">All</a></li>
                            {% for category in categories %}
                            <li>
                                <a
                                    href="{% url 'watches:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <hr class="my-4">

        <!-- Filter by Price Form -->
        <div class="bg-gray-200 p-4 rounded-lg">
            <h2 class="text-lg font-semibold text-gray-900 mb-4 text-center bitter-grey-medium">FILTER BY PRICE</h2>
            <div class="w-full flex flex-col items-center">
                <form method="get" action="{% url 'watches:filtered_watches_by_price' %}">
                    <label for="min_price" class="text-sm text-gray-700 "></label>
                    <input type="number"
                        class="ml-6 w-5/12 login-cursive text-center border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500"
                        name="min_price" id="min_price" placeholder="Minimum Price:">

                    <label for="max_price" class="text-sm text-gray-700 "></label>
                    <input type="number"
                        class="w-5/12 login-cursive text-center border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500"
                        name="max_price" id="max_price" placeholder="Maximum Price:">

                    <button type="submit" class="bitter-grey-medium w-full block mt-2">Apply Filter</button>
                </form>
            </div>
        </div>

        <!-- Filter by Year Form -->
        <div class="bg-gray-200 p-4 rounded-lg">
            <h2 class="text-lg font-semibold text-gray-900 mb-4 text-center bitter-grey-medium">FILTER BY YEAR</h2>
            <div class="w-full flex flex-col items-center">
                <form method="get" action="{% url 'watches:filtered_watches_by_year' %}">
                    <label for="min_year" class="text-sm text-gray-700 "></label>
                    <input type="number"
                        class="ml-6 w-5/12 login-cursive text-center border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 "
                        name="min_year" id="min_year" placeholder="Minimum Year:">

                    <label for="max_year" class="text-sm text-gray-700 "></label>
                    <input type="number"
                        class="w-5/12 login-cursive text-center border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 "
                        name="max_year" id="max_year" placeholder="Maximum Year:">

                    <button type="submit" class="bitter-grey-medium w-full block mt-2 ">Apply Filter</button>
                </form>
            </div>
        </div>
    </div>
    <div class="w-full flex justify-between items-center">
        <!-- Search bar -->
        <label for="search" class="sr-only bitter-grey-medium text-center text-gray-700">Search</label>
        <form method="get" action="{% url 'watches:search_items' %}" class="relative w-full md:w-1/2">
            <div class="flex flex-col md:flex-row items-center">
                <input type="search" id="search" name="query"
                    class="block w-full border border-gray-300 rounded-lg bitter-grey-medium text-lg text-center"
                    placeholder="Type & Search" required>
                <button type="submit"
                    class="md:w-1/3 w-full text-lg bitter-grey-medium border border-gray-300 bg-white rounded-md">Search</button>
            </div>
        </form>
    
        <!-- Clear button -->
        <div class="w-full md:w-1/2 px-2">
            <a href="{% url 'watches:items' %}"
                class="inline-block text-lg rounded-md w-full text-center bitter-grey-medium border border-gray-300 bg-white">
                Clear
            </a>
        </div>
    </div>
    
</div>

<!-- Available watches compartment -->
<div class="col-span-1 sm:col-span-3">
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
        {% for watch in items %}
        <div class="flex flex-col items-center">
            <a href="{% url 'watches:detail' watch.id %}">
                <div>
                    <img src="{{ watch.main_image.url }}" class="h-auto rounded-lg shadow-md" alt="{{ watch.name }}">
                </div>

                <div class="p-6 rounded-xl mt-4">
                    <h2 class="text-lg uppercase text-center span no-padding-margin">{{ watch.name }}</h2>
                    <p class="text-center font-semibold bitter-font-bold mt-4 no-padding-margin">Price :
                        {{ watch.price|intcomma }} <i class="fa-solid fa-sterling-sign"></i></p>
                    <p class="text-center mt-1 font-semibold bitter-font-bold no-padding-margin">Year :
                        <span class="text-center bitter-font-bold">{{ watch.year }} </span></p>
                    <div class="flex justify-center mt-2">
                        <div class="text-center mr-4 no-padding-margin"><span
                                class="font-semibold text-s bitter-font-bold">With
                                box</span>
                            {% if watch.has_box %}<span class="font-light text-s"><i
                                    class="fa-solid fa-circle-check"></i></span>
                            {% else %}<span class="font-light text-s"><i class="fa-regular fa-circle-xmark"></i></span>
                            {% endif %}
                        </div>

                        <div class="text-center no-padding-margin"><span
                                class="font-semibold text-s bitter-font-bold">With
                                papers</span>
                            {% if watch.has_papers %}<span class="font-light text-s"><i
                                    class="fa-solid fa-circle-check"></i></span>
                            {% else %}<span class="font-light text-s"><i class="fa-regular fa-circle-xmark"></i></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="flex flex-col items-center mt-2">
                        <p class="text-center text-xs no-padding-margin"><a href="{{ watch.ebay_link }}"
                                target="_blank"><i class="fa-brands fa-ebay text-4xl"></i></a></p>
                        <a href="{% url 'watches:submit_offer' watch.pk %}"
                            class="mt-2 px-4 py-1 font-semibold bg-gray-600 text-white hover:bg-teal-700 rounded-xl main-header-cursive no-padding-margin">Submit
                            an Offer</a>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

watches/templates/watches/submit_offer.html
<!-- watches/submit_offer.html -->

{% extends 'core/base.html' %}

{% block title %}Submit an Offer for {{ item.name }}{% endblock %}

{% block content %}
<section class="bg-gray-700">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <a href="#" class="flex items-center mb-6">
            <img class="h-20 mr-2 w-full" src="https://i.ibb.co/Vjcpfct/cover.png" alt="logo">
        </a>
        <div class="w-full md:mt-0 sm:max-w-md xl:p-0 bg-gray-700 ">
            <div class="text-center mb-2">
                <h1 class="bitter-grey-medium text-xl font-bold leading-tight tracking-tight md:text-2xl text-white">
                    Submit an Offer for {{ item.name }}
                </h1>
            </div>
            <!-- Container for the small photo of the watch with a fixed height -->
            <div class="max-w-md mx-auto mt-4 h-auto">
                <img src="{{ item.main_image.url }}" class="rounded-xl w-64 h-full mx-auto">
            </div>
            <form method="post" action="." class="mt-4">
                {% csrf_token %}
                <!-- Offer amount input -->
                <div>
                    <label for="offer_amount" class="bitter-grey-medium text-center block mb-2 text-sm font-semibold text-white">Your Offer Amount (£)</label>
                    <input type="text" name="offer_amount" id="offer_amount" class="bg-gray-600 border border-gray-300 text-gray-200 sm:text-sm rounded-lg block w-full p-2.5" required="" oninput="validateNumber(this)">
                </div>
                <button type="submit" class="w-full bitter-grey-medium text-sm mt-2 text-white ">Submit Offer</button>
            </form>
        </div>
    </div>
  </section>
  
{% endblock %}

watches/templates/watches/thanks.html
<!-- watches/thanks.html -->

{% extends 'core/base.html' %}

{% block title %}Thank You{% endblock %}

{% block content %}
<div class="m-4 md:m-20 p-4 md:p-20 rounded-xl bg-gradient-to-r from-gray-100 via-gray-300 to-black-200">
    <h2 class="mb-6 md:mb-12 text-2xl md:text-4xl text-center uppercase w-full" style="padding: 20px; font-family: Lato;"> Thank You for Your Offer</h2>
    <p class="text-center text-lg md:text-xl">Your offer has been submitted successfully.</p>
</div>
{% endblock %}