conversation/urls.py
from django.urls import path

from . import views
from .views import delete_conversation

app_name = 'conversation'


urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('conversation/<int:pk>/delete/', delete_conversation, name='delete_conversation'),
]

watches/urls.py
from django.urls import path

from . import views 

app_name = 'watches'

urlpatterns = [
    path('', views.filtered_items, name='items'), 
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/submit_offer/', views.submit_offer, name='submit_offer'),
    path('watches/category/<str:category_name>/', views.filtered_items, name='watches_by_category'),  
    path('watches/filter/price/', views.filtered_items, name='filtered_watches_by_price'), 
    path('filtered_watches_by_year/', views.filtered_items, name='filtered_watches_by_year'),
    path('search/', views.search_items, name='search_items'),
] 

watchsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('watchapp.urls')),
    path('watches/', include('watches.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/models.py
from django.contrib.auth.models import User
from django.db import models

from watches.models import Item

class Conversation(models.Model):
    item = models.ForeignKey(Item, related_name='conversations', on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='conversations')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-modified_at',)

    def __str__(self):
        return f'Conversation about {self.item.name}'

class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE)
    is_offer = models.BooleanField(default=False)

    def __str__(self):
        return self.content[:50]
    
    MESSAGE_TYPE_CHOICES = [
        ('message', 'Message'),
        ('offer', 'Offer'),
    ]
    
    message_type = models.CharField(max_length=7, choices=MESSAGE_TYPE_CHOICES, default='message')
    
    @classmethod
    def create_offer(cls, conversation, content, created_by):
        return cls.objects.create(
            conversation=conversation,
            content=content,
            created_by=created_by,
            message_type='offer'  # Set the message type to 'offer'
        )

conversation/forms.py
from django import forms    
from .models import ConversationMessage



class ConversationMessageForm(forms.ModelForm):
    is_offer = forms.BooleanField(
        required=False,
        widget=forms.HiddenInput,  # Use a hidden input field
        initial=False,  # Default to False (not an offer)
    )
    class Meta:
        model = ConversationMessage
        fields = ['content', 'is_offer']
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

conversation/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from watches.models import Item, Category
from .forms import ConversationMessageForm
from .models import Conversation
from watches.models import Offer

@login_required
def new_conversation(request, item_pk):
    item = get_object_or_404(Item, pk=item_pk)
    categories = Category.objects.all()

    if item.created_by == request.user:
        return redirect('conversation:inbox')

    # Check if a conversation with the same members already exists
    conversations = Conversation.objects.filter(item=item, members=request.user)
    
    if conversations.exists():
        # Redirect to the existing conversation
        return redirect('conversation:detail', conversations.first().id)
    
    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            is_offer = form.cleaned_data.get('is_offer', False)  # Get the offer flag
            # Create a new conversation
            conversation = Conversation.objects.create(item=item)
            conversation.members.add(request.user)
            conversation.members.add(item.created_by)
            
            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.is_offer = is_offer  # Set the offer flag
            conversation_message.save()

            return redirect('watches:detail', pk=item_pk)
    else:
        form = ConversationMessageForm()
    
    return render(request, 'conversation/new.html', {
        'form': form,
        'categories': categories,

    })


@login_required
def inbox(request):
    conversations = Conversation.objects.filter(members=request.user)
    categories = Category.objects.all()

    offer_messages = []

    for conversation in conversations:
        messages = conversation.messages.filter(is_offer=True)  # Filter messages where is_offer is True
        if messages.exists():
            offer_messages.extend(messages)

    return render(request, 'conversation/inbox.html', {
        'conversations': conversations,
        'offer_messages': offer_messages,
        'categories': categories,
    })


@login_required
def detail(request, pk):
    conversation = get_object_or_404(Conversation, pk=pk, members=request.user)
    form = ConversationMessageForm()
    categories = Category.objects.all()

    if request.method =='POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.save()

            return redirect('conversation:detail', pk=pk)

    messages = conversation.messages.all()

    return render(request, 'conversation/detail.html', {
        'conversation': conversation,
        'form': form,
        'messages': messages,
        'categories': categories,
    })

@login_required
def delete_conversation(request, pk):
    conversation = get_object_or_404(Conversation, pk=pk)
    
    # Check if the current user is a member of the conversation
    if request.user in conversation.members.all():
        # Delete the conversation
        conversation.delete()
    
    return redirect('conversation:inbox')

conversation/templates/conversation/detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %} Conversation {% endblock %}

{% block content %}
<h1 class="text-6xl main-header-cursive text-center mb-5"> Conversation </h1>

<div class="space-y-6">
    {% for message in conversation.messages.all %}
    <div class="p-6 flex {% if message.created_by == request.user %}bg-blue-100 {% else %}bg-gray-100 rounded-xl {% endif %}">
        <div>
            <p class="mb-4 text-center">
                <strong class="text-black bitter-grey-medium text-xl"> USER - {{ message.created_by.username }}  </strong> <span class="text-base"> Has sent a message on : {{ message.created_at }} </span> <!--to {{ conversation.item.created_by.username }} -->
                {% if message.is_offer %}
                <p class="offer-message">
                    <span class="text-2xl mr-2 bitter-grey-medium"><i class="fa-solid fa-scale-unbalanced-flip mr-4"> </i>I have a price proposal for :  {{ conversation.item.name }}</span>
                    <hr>
                    <div class="text-center"> <!-- Wrap the content in a block-level container -->
                        <span class="bitter-grey-medium text-2xl">{{ message.content }}</span>
                    </div>
                </p>
                {% else %}
                <p>{{ message.content }}</p>
                {% endif %}
            </p>
        </div>
    </div>
    {% endfor %}
</div>

<form method="post" action="." class="mt-10">
    {% csrf_token %}

    {{ form.content }}


    <button class="mt-2 px-4 py-1 font-semibold bg-gray-600 text-white hover:bg-teal-700 rounded-xl main-header-cursive mb-5">Send</button>
</form>

<a href="{% url 'conversation:inbox' %}" class="mt-2 px-4 py-2 font-semibold bg-gray-600 text-white hover:bg-teal-700 rounded-xl main-header-cursive">Return to Inbox</a>
{% endblock %}

conversation/templates/conversation/inbox.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %} Inbox {% endblock %}

{% block content %}
<h1 class="mb-6 text-6xl main-header-cursive text-center"> <i class="fa-regular fa-envelope mr-4"></i> Inbox </h1>

<div class="space-y-6">
    {% for conversation in conversations %}
        <a href="{% url 'conversation:detail' conversation.id %}">
            <div class="p-6 flex bg-gray-100 rounded-xl">
                <div class="pr-6">
                    <img src="{{ conversation.item.main_image.url }}" class="w-20 rounded-xl">
                </div>
                <div class="flex flex-col">
                    {% with latest_message=conversation.messages.all|dictsort:"created_at"|last %}
                        <p class="mb-4"><strong class="bitter-black-large">
                            {{ latest_message.created_by.username }}
                            Has sent a message to
                            {% if latest_message.created_by != request.user %}
                                {{ request.user.username }}
                            {% else %}
                                {% for member in conversation.members.all %}
                                    {% if member != request.user %}
                                        {{ member.username }}
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            on :
                        </strong> | {{ latest_message.created_at }}</p>
                    {% endwith %}
                    <p class="bitter-grey-medium">{{ conversation.item.name }}</p>

                    <!-- Display all offer messages for this conversation -->
                    {% for offer_message in offer_messages %}
                        {% if offer_message.conversation == conversation %}
                            <div class="offer">
                                <p><strong class="bitter-grey-medium">New price suggestion :
                                    <i class="fa-solid fa-scale-unbalanced-flip"> </i>
                                </strong> <span class="bitter-grey-medium">{{ offer_message.content }}</span> </p>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <!-- Add a container for the buttons to appear inline -->
                    <div class="flex space-x-2 mt-2">
                        <!-- Add a form for viewing the conversation -->
                        <form method="post" action="{% url 'conversation:detail' conversation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="bg-green-500 text-white px-3 py-1 rounded-md">View Conversation</button>
                        </form>

                        <!-- Add a form for deleting the conversation -->
                        <form method="post" action="{% url 'conversation:delete_conversation' conversation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="bg-gray-700 text-white px-3 py-1 rounded-md">Delete Conversation</button>
                        </form>
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
</div>




{% endblock %}

conversation/templates/conversation/new.html
{% extends 'core/base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">

{% block title %} New Conversation {% endblock %}

{% block content %}
<h1 class="text-6xl main-header-cursive text-center mb-5"> New Conversation </h1>

<div class="space-y-6">
    {% for message in conversation.messages.all %}
    <div class="p-6 flex {% if message.created_by == request.user %}bg-blue-100 {% else %}bg-gray-100 rounded-xl {% endif %}">
        <div>
            <p class="mb-4 text-center">
                <strong class="main-header-cursive text-3xl mr-3">{{ message.created_by.username }}</strong> <span class="text-xs"> Has sent you a message on : {{ message.created_at }} </span>
                {% if message.is_offer %}
                <p class="offer-message">
                    <strong class="text-2xl mr-2 bitter-grey-medium">I have a price proposal for: {{ conversation.item.name }}</strong>
                    <hr>
                    <div class="text-center"> <!-- Wrap the content in a block-level container -->
                        <span class="bitter-grey-medium text-2xl">{{ message.content }}</span>
                    </div>
                </p>
                {% else %}
                <p>{{ message.content }}</p>
                {% endif %}
            </p>
        </div>
    </div>
    {% endfor %}
</div>

<form method="post" action="." class="mt-10">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.content }}
    </div>

    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}

        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <button class="mb-4 px-4 py-2 font-semibold bg-gray-600 text-white hover:bg-teal-700 rounded-xl main-header-cursive">Send</button>
</form>

<a href="{% url 'conversation:inbox' %}" class="mt-2 px-4 py-2 font-semibold bg-gray-600 text-white hover:bg-teal-700 rounded-xl main-header-cursive">Return to Inbox</a>
{% endblock %}